// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJT-o3AQwpB6dX0ZV1NM98vfxwmd0BZo',
    appId: '1:24990764892:web:8b94c72da1c5046dbe3b99',
    messagingSenderId: '24990764892',
    projectId: 'project2-de4e8',
    authDomain: 'project2-de4e8.firebaseapp.com',
    storageBucket: 'project2-de4e8.appspot.com',
    measurementId: 'G-KR0G1PLSRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALKI5CK3xSu1AzhOn8H26AnyBSTECbQmc',
    appId: '1:24990764892:android:3dde5f9c0e14b6b6be3b99',
    messagingSenderId: '24990764892',
    projectId: 'project2-de4e8',
    storageBucket: 'project2-de4e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yAa6trHka27uphsqT1MFzasu6U_hc6g',
    appId: '1:24990764892:ios:b0518a3d6ed65636be3b99',
    messagingSenderId: '24990764892',
    projectId: 'project2-de4e8',
    storageBucket: 'project2-de4e8.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yAa6trHka27uphsqT1MFzasu6U_hc6g',
    appId: '1:24990764892:ios:a06f7e63ba73e731be3b99',
    messagingSenderId: '24990764892',
    projectId: 'project2-de4e8',
    storageBucket: 'project2-de4e8.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
